# Generated by Django 4.2.6 on 2023-11-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_ap_materno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ap_materno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='ap_paterno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
